### ISSUE TITLE
Avoid targeting security hazards

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl-v2#6]
Kubeconfigs, that are fetched by gardenctl should not contain any credentials that the user could leak

Tasks to get safe Shoot kubeconfigs:
- [x] [implement gardenlogin kubectl auth plugin](https://github.com/gardener/garden-login/pull/1)
- [x] [gardenlogin-controller-manager to generate safe kubeconfigs](https://github.com/gardener/gardenlogin-controller-manager/issues/2)
- [x] [add landscaper component for gardenlogin-controller-manager](https://github.com/gardener/gardenlogin-controller-manager/issues/4)
- [x] increase default quotas for configmaps (internally)
- [x] use in gardenctl-v2

Tasks to get safe Seed kubeconfigs
- [x] Generate and write `<seed-name>.oidc` kubeconfigs for seeds to garden cluster (internally)
- [x] use oidc kubeconfigs in gardenctl-v2

**Comment by petersutter** [comment]
/close

`gardenlogin` shoot kubeconfigs and oidc seed kubeconfigs now consumed with #61
